#lang planet neil/sicp
;a)
(define (make-sum a1 a2)
  (list a1 '+ a2))
(define (make-product m1 m2)
  (list m1 '* m2))
(define (sum? x)
  (and (pair? x) (pair? (cdr x)) (eq? (cadr x) '+)))
(define (addend s)
  (car s))
(define (augend s)
  (caddr s))
(define (product? x)
  (and (pair? x) (pair? (cdr x)) (eq? (cadr x) '*)))
(define (multiplier p)
  (car p))
(define (multiplicand p)
  (caddr p))