#lang planet neil/sicp
(define (encode-symbol char tree)
  (define (iter char current-branch)
    (if (leaf? current-branch)
        '()
        (let ((left (left-branch current-branch))
              (right (right-branch current-branch)))
          (if (element-of-set? char left)
              (cons 0 (iter char left))
              (cons 1 (iter char right))))))
  (if (element-of-set? char (symbols tree))
      (iter char tree)
      (error "-- is not in this tree" char)))

(define (encode message tree)
  (if (null? message)
      '()
      (append (encode-symbol (car message) tree)
              (encode (cdr message tree)))))