#lang planet neil/sicp
(define (count-change amount)
  (define (cc amount kinds-of-coins)
    (cond ((= amount 0) 1)
          ((or (< amount 0) (= kinds-of-coins 0)) 0)
          (else (+ (cc amount (- kinds-of-coins 1))
                   (cc (- amount (first-denomination kinds-of-coins))
                       kinds-of-coins)))))
  (define (first-denomination kinds)
    (cond ((= kinds 1) 1)
          ((= kinds 2) 5)
          ((= kinds 3) 10)
          ((= kinds 4) 25)
          ((= kinds 5) 50)))
  (cc amount 5))
(count-change 100)
