#lang planet neil/sicp
(define (install-scheme-package)
  (define (=zero? x)
    (= x 0))
  (put '=zero? '(scheme-number)
       =zero?)
  'done)

(define (install-rational-package)
  (define (=zero? x)
    (= (numer x) 0))
  (put '=zero? '(rational)
       =zero?)
  'done)

(define (install-rational-package)
  (define (=zero? x)
    (and (= (imag-part x) 0)
         (= (real-part x) 0)))
  (put '=zero? '(complex)
       =zero?)
  'done)
(define (=zero? x)
  (apply-generic '=zero? x))
