#lang planet neil/sicp
(define (make-account balance code)
  (define (call-the-cops)
    (error "Called the cops"))
  (let ((times 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch c m)
      (if (eq? c code)
          (begin (set! times 0)
                 (cond ((eq? m 'withdraw) withdraw)
                       ((eq? m 'deposit) deposit)
                       (else (error "Unknown request -- MAKE-ACCOUNT"
                                    m))))
          (lambda (amount)
            (if (>= times 7)
                (call-the-cops)
                (begin (set! times (+ times 1))
                       (display times)
                       (display "Incorrect code\n"))))))
    dispatch))
(define acc (make-account 100 'secret-password))
((acc 'secret-passwor 'withdraw) 40)
((acc 'secret-passwor 'withdraw) 40)
((acc 'secret-passwor 'withdraw) 40)
((acc 'secret-passwor 'withdraw) 40)
((acc 'secret-passwor 'withdraw) 40)
((acc 'secret-passwor 'withdraw) 40)
((acc 'secret-passwor 'withdraw) 40)
((acc 'secret-passwor 'withdraw) 40)