#lang planet neil/sicp
(define (make-account balance code)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch c m)
    (if (eq? c code)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request -- MAKE-ACCOUNT"
                           m)))
        (error "Incorrect code")))
  dispatch)
(define (make-joint acc code new-code)
  (define (dispatch c m)
    (if (eq? c new-code)
        (acc code m)
        (error "Incorrect code")))
  dispatch)
(define peter-acc (make-account 100 'a))
((peter-acc 'a 'withdraw) 20)
(define paul-acc (make-joint peter-acc 'a 'b))
((paul-acc 'b 'withdraw) 20)
((peter-acc 'a 'withdraw) 20)
